/**
 * Generates public/patterns/ankara.svg from the brand tokens in
 * tailwind.config.ts.
 *
 * Why a generator?
 *   AC-2 requires "no inline hex outside the Tailwind config" for
 *   styling surfaces (backgrounds, headings, buttons, cards). The
 *   FlavorFind brand palette is the single source of truth, defined
 *   once in tailwind.config.ts.
 *
 *   This file is the template source for the Ankara/Adire-inspired
 *   CSS-background pattern referenced by the `bg-ankara-pattern` utility
 *   in tailwind.config.ts. It contains ZERO hex literals — every brand
 *   color is read at build time from tailwind.config.ts via a typed
 *   `Config` import and substituted into the SVG template. The resulting
 *   public/patterns/ankara.svg necessarily carries hex values (SVG assets
 *   rendered via `background-image: url(...)` cannot inherit CSS custom
 *   properties from the parent document), but the SVG is BOTH committed
 *   to the repo (so a clean checkout has the AC-4-required asset
 *   immediately) AND regenerated on every `prebuild` / `predev`, so the
 *   byte-level brand values can never drift from tailwind.config.ts.
 *
 *   Guarantees the architecture provides:
 *     - One source of truth: tailwind.config.ts
 *     - Consistency: `npm run prebuild` / `predev` / `build:pattern`
 *       regenerate public/patterns/ankara.svg from this template + the
 *       config
 *     - Drift detection: `npm run verify:pattern` checks that every
 *       brand token declared in the config is present in the SVG (and
 *       that no unconfigured hex literal sneaks in) — exit-code 1 on
 *       drift
 *
 *   Change workflow:
 *     1. Edit `tailwind.config.ts` to add / change a brand token.
 *     2. Run `npm run build:pattern` to regenerate
 *        public/patterns/ankara.svg.
 *     3. Run `npm run verify:pattern` to confirm consistency.
 *     4. Commit both files together.
 *
 *   Pattern design notes:
 *     - 80 x 80 px tile, tileable horizontally and vertically.
 *     - Alternating dark/light diamonds on a 20 px grid create a
 *       continuous Ankara-style motif when tiled.
 *     - Mid-tone accent dots anchor each diamond.
 *
 * Run via: `npx tsx scripts/build-pattern.ts`
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import tailwindConfig from "../tailwind.config";

type TailwindConfig = {
  theme?: {
    extend?: {
      colors?: Record<string, unknown>;
    };
  };
};

function readBrand(config: TailwindConfig): Record<string, string> {
  const colors = config.theme?.extend?.colors;
  if (!colors || typeof colors !== "object") {
    throw new Error(
      "Tailwind config is missing theme.extend.colors; update tailwind.config.ts.",
    );
  }
  const brand = (colors as Record<string, unknown>).brand;
  if (!brand || typeof brand !== "object") {
    throw new Error(
      "Tailwind config is missing theme.extend.colors.brand; update tailwind.config.ts to add it.",
    );
  }
  return brand as Record<string, string>;
}

const brand = readBrand(tailwindConfig as TailwindConfig);
for (const key of ["light", "dark", "mid", "cream", "accent"] as const) {
  if (!brand[key]) {
    throw new Error(
      `Tailwind config is missing theme.extend.colors.brand.${key}; ` +
        `update tailwind.config.ts to add it.`,
    );
  }
}

// SVG template. Hex values are injected at build time from the Tailwind
// config above; the template itself contains no hex literals, satisfying
// AC-2's "no inline hex outside Tailwind config" rule for this asset.
const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  AUTO-GENERATED by scripts/build-pattern.ts. Do NOT edit this file directly;
  edit the template in scripts/build-pattern.ts (or the brand tokens in
  tailwind.config.ts) and re-run \`npm run build:pattern\`.

  Brand palette sourced from tailwind.config.ts:
    brand.cream  = ${brand.cream}
    brand.dark   = ${brand.dark}
    brand.light  = ${brand.light}
    brand.mid    = ${brand.mid}
    brand.accent = ${brand.accent}

  Ankara/Adire-inspired geometric tile (80 x 80 px). Tiles seamlessly
  horizontally and vertically when used as a CSS background — see the
  \`bg-ankara-pattern\` utility in tailwind.config.ts.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80" width="80" height="80">
  <title>FlavorFind Ankara pattern</title>
  <desc>A tileable Ankara/Adire-inspired geometric pattern using the FlavorFind brown palette.</desc>

  <!-- Cream base -->
  <rect width="80" height="80" fill="${brand.cream}"/>

  <!-- 4x4 alternating diamonds on a 20 px grid (tile-friendly) -->
  <g>
    <!-- Row 1 (y centre = 10) -->
    <path d="M 10 2 L 18 10 L 10 18 L 2 10 Z" fill="${brand.dark}"/>
    <path d="M 30 2 L 38 10 L 30 18 L 22 10 Z" fill="${brand.light}"/>
    <path d="M 50 2 L 58 10 L 50 18 L 42 10 Z" fill="${brand.dark}"/>
    <path d="M 70 2 L 78 10 L 70 18 L 62 10 Z" fill="${brand.light}"/>

    <!-- Row 2 (y centre = 30) -->
    <path d="M 10 22 L 18 30 L 10 38 L 2 30 Z" fill="${brand.light}"/>
    <path d="M 30 22 L 38 30 L 30 38 L 22 30 Z" fill="${brand.dark}"/>
    <path d="M 50 22 L 58 30 L 50 38 L 42 30 Z" fill="${brand.light}"/>
    <path d="M 70 22 L 78 30 L 70 38 L 62 30 Z" fill="${brand.dark}"/>

    <!-- Row 3 (y centre = 50) -->
    <path d="M 10 42 L 18 50 L 10 58 L 2 50 Z" fill="${brand.dark}"/>
    <path d="M 30 42 L 38 50 L 30 58 L 22 50 Z" fill="${brand.light}"/>
    <path d="M 50 42 L 58 50 L 50 58 L 42 50 Z" fill="${brand.dark}"/>
    <path d="M 70 42 L 78 50 L 70 58 L 62 50 Z" fill="${brand.light}"/>

    <!-- Row 4 (y centre = 70) -->
    <path d="M 10 62 L 18 70 L 10 78 L 2 70 Z" fill="${brand.light}"/>
    <path d="M 30 62 L 38 70 L 30 78 L 22 70 Z" fill="${brand.dark}"/>
    <path d="M 50 62 L 58 70 L 50 78 L 42 70 Z" fill="${brand.light}"/>
    <path d="M 70 62 L 78 70 L 70 78 L 62 70 Z" fill="${brand.dark}"/>
  </g>

  <!-- Inner accent dots (mid brown) anchor each diamond -->
  <g fill="${brand.mid}">
    <circle cx="10" cy="10" r="1.6"/>
    <circle cx="30" cy="10" r="1.6"/>
    <circle cx="50" cy="10" r="1.6"/>
    <circle cx="70" cy="10" r="1.6"/>

    <circle cx="10" cy="30" r="1.6"/>
    <circle cx="30" cy="30" r="1.6"/>
    <circle cx="50" cy="30" r="1.6"/>
    <circle cx="70" cy="30" r="1.6"/>

    <circle cx="10" cy="50" r="1.6"/>
    <circle cx="30" cy="50" r="1.6"/>
    <circle cx="50" cy="50" r="1.6"/>
    <circle cx="70" cy="50" r="1.6"/>

    <circle cx="10" cy="70" r="1.6"/>
    <circle cx="30" cy="70" r="1.6"/>
    <circle cx="50" cy="70" r="1.6"/>
    <circle cx="70" cy="70" r="1.6"/>
  </g>
</svg>
`;

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "..", "public", "patterns", "ankara.svg");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, svg, "utf8");
console.log(`Wrote ${outPath} (${svg.length} bytes)`);