/**
 * Generates public/logo.svg from the brand tokens in tailwind.config.ts.
 *
 * Why a generator?
 *   AC-2 requires "no inline hex outside the Tailwind config" for
 *   styling surfaces (backgrounds, headings, buttons, cards). The
 *   FlavorFind brand palette is the single source of truth, defined
 *   once in tailwind.config.ts.
 *
 *   This file is the template source for the SVG artwork. It contains
 *   ZERO hex literals — every brand color is read at build time from
 *   tailwind.config.ts via a typed `Config` import and substituted into
 *   the SVG template. The resulting public/logo.svg necessarily carries
 *   hex values (SVG assets rendered via `<img>` cannot inherit CSS
 *   custom properties from the parent document), but the SVG is BOTH
 *   committed to the repo (so a clean checkout has the AC-3-required
 *   asset immediately) AND regenerated on every `prebuild` / `predev`,
 *   so the byte-level brand values can never drift from
 *   tailwind.config.ts.
 *
 *   Guarantees the architecture provides:
 *     - One source of truth: tailwind.config.ts
 *     - Consistency: `npm run prebuild` / `predev` / `build:logo`
 *       regenerate public/logo.svg from this template + the config
 *     - Drift detection: `npm run verify:logo` checks that every brand
 *       token declared in the config is present in the SVG (and that no
 *       unconfigured hex literal sneaks in) — exit-code 1 on drift
 *
 *   Change workflow:
 *     1. Edit `tailwind.config.ts` to add / change a brand token.
 *     2. Run `npm run build:logo` to regenerate public/logo.svg.
 *     3. Run `npm run verify:logo` to confirm consistency.
 *     4. Commit both files together.
 *
 * Run via: `npx tsx scripts/build-logo.ts`
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import tailwindConfig from "../tailwind.config";

type TailwindConfig = {
  theme?: {
    extend?: {
      colors?: Record<string, unknown>;
    };
  };
};

function readBrand(config: TailwindConfig): Record<string, string> {
  const colors = config.theme?.extend?.colors;
  if (!colors || typeof colors !== "object") {
    throw new Error(
      "Tailwind config is missing theme.extend.colors; update tailwind.config.ts.",
    );
  }
  const brand = (colors as Record<string, unknown>).brand;
  if (!brand || typeof brand !== "object") {
    throw new Error(
      "Tailwind config is missing theme.extend.colors.brand; update tailwind.config.ts to add it.",
    );
  }
  return brand as Record<string, string>;
}

const brand = readBrand(tailwindConfig as TailwindConfig);
for (const key of ["light", "dark", "mid"] as const) {
  if (!brand[key]) {
    throw new Error(
      `Tailwind config is missing theme.extend.colors.brand.${key}; ` +
        `update tailwind.config.ts to add it.`,
    );
  }
}

// SVG template. Hex values are injected at build time from the Tailwind
// config above; the template itself contains no hex literals, satisfying
// AC-2's "no inline hex outside Tailwind config" rule for this asset.
const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  AUTO-GENERATED by scripts/build-logo.ts. Do NOT edit this file directly;
  edit the template in scripts/build-logo.ts (or the brand tokens in
  tailwind.config.ts) and re-run \`npm run build:logo\`.

  Brand palette sourced from tailwind.config.ts:
    brand.dark  = ${brand.dark}
    brand.light = ${brand.light}
    brand.mid   = ${brand.mid}
-->
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 320 96"
     role="img"
     aria-label="FlavorFind logo">
  <title>FlavorFind</title>
  <desc>A hand-drawn bowl with steam and a resting spoon, paired with the FlavorFind wordmark.</desc>

  <!-- ===== Mark: bowl + spoon glyph (local coords 0..80 x 0..80) ===== -->
  <g transform="translate(8,8)">
    <!-- Steam wisps rising from the bowl -->
    <g fill="none" stroke="${brand.light}" stroke-width="2.25" stroke-linecap="round">
      <path d="M28 22 C 24 16, 32 12, 28 6"/>
      <path d="M40 22 C 36 16, 44 12, 40 6"/>
      <path d="M52 22 C 48 16, 56 12, 52 6"/>
    </g>

    <!-- Bowl body (truncated hemisphere) -->
    <path d="M14 36 H 66 L 60 60 Q 40 70, 20 60 Z"
          fill="${brand.dark}"
          stroke="${brand.dark}"
          stroke-width="2"
          stroke-linejoin="round"/>

    <!-- Bowl rim (top ellipse, mid tone to suggest depth) -->
    <ellipse cx="40" cy="36" rx="26" ry="5.5"
             fill="${brand.mid}"
             stroke="${brand.dark}"
             stroke-width="2"/>

    <!-- Geometric chevron band around the bowl (subtle African-pattern nod) -->
    <g fill="${brand.light}">
      <path d="M17 47 L 22 43 L 27 47 L 22 51 Z"/>
      <path d="M27 47 L 32 43 L 37 47 L 32 51 Z"/>
      <path d="M37 47 L 42 43 L 47 47 L 42 51 Z"/>
      <path d="M47 47 L 52 43 L 57 47 L 52 51 Z"/>
      <path d="M57 47 L 62 43 L 63 47 L 60 51 Z"/>
    </g>

    <!-- Spoon: oval bowl resting on the rim, handle angling up-right -->
    <g>
      <ellipse cx="38" cy="36" rx="7" ry="4.5"
               fill="${brand.light}"
               stroke="${brand.dark}"
               stroke-width="2"
               transform="rotate(-30 38 36)"/>
      <line x1="44" y1="32" x2="66" y2="10"
            stroke="${brand.dark}"
            stroke-width="4"
            stroke-linecap="round"/>
    </g>
  </g>

  <!-- ===== Wordmark ===== -->
  <g transform="translate(96,0)">
    <text x="0" y="52"
          font-family="Georgia, 'Cambria', 'Times New Roman', serif"
          font-size="34"
          font-weight="700"
          letter-spacing="0.5"
          fill="${brand.dark}">Flavor<tspan fill="${brand.light}">Find</tspan></text>
    <text x="2" y="70"
          font-family="ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif"
          font-size="9"
          font-weight="600"
          letter-spacing="3"
          fill="${brand.mid}">EAT &#183; NIGERIA</text>
  </g>
</svg>
`;

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "..", "public", "logo.svg");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, svg, "utf8");
console.log(`Wrote ${outPath} (${svg.length} bytes)`);
